### ISSUE TITLE
Rc file failure

### ISSUE THREAD

**Issue by Arqib** [luckboy/rsush#3]
Creating a .rsushrc file make rsush crash the next time you open it. The minute you delete it does not crash. This also applies to /etc/rsushrc. Even is the file is empty, it still crashes. Am I doing something wrong or is this a valid bug?

**Comment by Arqib** [comment]
~~~
[2]+  Stopped                 rsush
~~~

**Comment by luckboy** [comment]
I fixed this bug of double signal initializing. Shell doubly initialized signals: one for interactive mode, two for script mode.
Initialization of script mode doesn't ignore SIGTTIN and SIGTTOU signals.

**Comment by Arqib** [comment]
I have confirmed that this issue is fixed. Thanks.
